# Generated by Django 3.1.3 on 2021-04-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
