# Generated by Django 3.2 on 2021-04-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customeruser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='universitet',
            field=models.CharField(default='universitet', max_length=200),
            preserve_default=False,
        ),
    ]
